# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

services:
  - postgresql

before_install:
  - psql -c 'create database car;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
#after_success:
#  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - senebh@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
   CODECOV_TOKEN="2495c869-8236-44bc-a728-76e7d223106f"